package dev.kubisiak.MyF.common;

public enum ErrorMessageInformation {

    INTERNAL_SERVER_ERROR,
    SENDER_NOT_FOUND,
    INVITED_USER_NOT_FOUND,
    INVITATION_WAS_ALREADY_SENT,
    USER_ARE_ALREADY_FRIENDS, USER_IS_NOT_RECIPIENT_OF_INVITATION, INVITATION_STATUS_IS_NOT_VALID, INVITATION_WAS_NOT_FOUND, AUTHENTICATED_USER_NOT_FOUND,

}
